#ifndef SIGNALPOOLS_GLOBAL_H
#define SIGNALPOOLS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIGNALPOOLS_LIBRARY)
#  define SIGNALPOOLSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SIGNALPOOLSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SIGNALPOOLS_GLOBAL_H
